(() => {
  const STORAGE_KEY = "taskflow.tasks.v1";
  const state = { tasks: loadTasks(), status: "all", filter: "all", query: "", sort: "created", editingId: null, deletedTasks: [] };
  const elements = {
    form: document.querySelector("#task-form"), title: document.querySelector("#task-title"), category: document.querySelector("#task-category"), priority: document.querySelector("#task-priority"), dueDate: document.querySelector("#task-date"), recurrence: document.querySelector("#task-recurrence"), submit: document.querySelector("#submit-task"), cancelEdit: document.querySelector("#cancel-edit"), list: document.querySelector("#task-list"), empty: document.querySelector("#empty-state"), emptyTitle: document.querySelector("#empty-title"), emptyCopy: document.querySelector("#empty-copy"), emptyAction: document.querySelector("#empty-action"), search: document.querySelector("#search-input"), sort: document.querySelector("#sort-select"), viewLabel: document.querySelector("#view-label"), todayLabel: document.querySelector("#today-label"), progressRing: document.querySelector("#progress-ring"), progressValue: document.querySelector("#progress-value"), progressCopy: document.querySelector("#progress-copy"), toast: document.querySelector("#toast"), toastMessage: document.querySelector("#toast-message"), toastAction: document.querySelector("#toast-action")
  };
  const statusLabels = { all: "All tasks", today: "Today", upcoming: "Upcoming", completed: "Completed" };
  const categoryLabels = { work: "Work", personal: "Personal", health: "Health", learning: "Learning" };
  const priorityRank = { high: 0, medium: 1, low: 2 };
  let toastTimer;

  function loadTasks() {
    try { const saved = JSON.parse(localStorage.getItem(STORAGE_KEY)); return Array.isArray(saved) ? saved.filter((task) => task && typeof task === "object").map(normalizeTask) : []; } catch { return []; }
  }
  function normalizeTask(task) { return { id: String(task.id || crypto.randomUUID()), title: String(task.title || "Untitled task"), completed: Boolean(task.completed), category: categoryLabels[task.category] ? task.category : "work", priority: priorityRank[task.priority] !== undefined ? task.priority : "medium", dueDate: /^\d{4}-\d{2}-\d{2}$/.test(task.dueDate || "") ? task.dueDate : "", recurrence: ["none", "daily", "weekly", "monthly"].includes(task.recurrence) ? task.recurrence : "none", createdAt: Number(task.createdAt) || Date.now(), updatedAt: Number(task.updatedAt) || Date.now() }; }
  function saveTasks() { try { localStorage.setItem(STORAGE_KEY, JSON.stringify(state.tasks)); return true; } catch { showToast("Tasks could not be saved in this browser."); return false; } }
  function dateKey(date = new Date()) { const local = new Date(date.getTime() - date.getTimezoneOffset() * 60000); return local.toISOString().slice(0, 10); }
  function parseDate(value) { return value ? new Date(`${value}T12:00:00`) : null; }
  function formatDate(value) { const date = parseDate(value); if (!date) return "No due date"; return date.toLocaleDateString(undefined, { month: "short", day: "numeric" }); }
  function isToday(task) { return task.dueDate === dateKey(); }
  function isUpcoming(task) { return task.dueDate && task.dueDate > dateKey() && !task.completed; }
  function visibleTasks() {
    const query = state.query.trim().toLowerCase();
    return state.tasks.filter((task) => {
      const matchesStatus = state.status === "all" || (state.status === "today" && isToday(task) && !task.completed) || (state.status === "upcoming" && isUpcoming(task)) || (state.status === "completed" && task.completed);
      const matchesFilter = state.filter === "all" || task.priority === state.filter || task.category === state.filter;
      const matchesQuery = !query || `${task.title} ${task.category} ${task.priority}`.toLowerCase().includes(query);
      return matchesStatus && matchesFilter && matchesQuery;
    }).sort((a, b) => { if (state.sort === "due") return (a.dueDate || "9999") .localeCompare(b.dueDate || "9999"); if (state.sort === "priority") return priorityRank[a.priority] - priorityRank[b.priority]; if (state.sort === "alphabetical") return a.title.localeCompare(b.title); return b.createdAt - a.createdAt; });
  }
  function render() { renderCounts(); renderTasks(); renderProgress(); elements.viewLabel.textContent = statusLabels[state.status]; }
  function renderCounts() { const counts = { all: state.tasks.filter((task) => !task.completed).length, today: state.tasks.filter((task) => isToday(task) && !task.completed).length, upcoming: state.tasks.filter(isUpcoming).length, completed: state.tasks.filter((task) => task.completed).length }; Object.entries(counts).forEach(([key, value]) => { const el = document.querySelector(`#${key}-count`); if (el) el.textContent = value; }); }
  function renderTasks() { const tasks = visibleTasks(); elements.list.innerHTML = tasks.map(taskTemplate).join(""); const hasTasks = tasks.length > 0; elements.list.classList.toggle("hidden", !hasTasks); elements.empty.classList.toggle("hidden", hasTasks); if (!hasTasks) { const filtered = state.query || state.filter !== "all" || state.status !== "all"; elements.emptyTitle.textContent = filtered ? "No matching tasks" : "Nothing here yet"; elements.emptyCopy.textContent = filtered ? "Try changing your search or filters." : "Add your first task and give your day a little direction."; elements.emptyAction.textContent = filtered ? "Show all tasks" : "Create a task"; } }
  function taskTemplate(task) { const dueClass = task.dueDate < dateKey() && !task.completed ? "due-overdue" : isToday(task) ? "due-today" : ""; const recurrence = task.recurrence !== "none" ? `<span>↻ ${escapeHtml(task.recurrence)}</span>` : ""; return `<article class="task-card ${task.completed ? "completed" : ""}" data-id="${escapeHtml(task.id)}"><div class="task-main"><button class="complete-button" type="button" data-action="toggle" aria-label="${task.completed ? "Mark incomplete" : "Mark complete"}">${task.completed ? "✓" : ""}</button><div class="task-content"><h3 class="task-title">${escapeHtml(task.title)}</h3><div class="task-meta"><span class="task-tag">${categoryLabels[task.category]}</span><span class="task-tag priority-${task.priority}">${task.priority} priority</span><span class="${dueClass}">${task.dueDate ? `Due ${formatDate(task.dueDate)}` : "No due date"}</span>${recurrence}</div></div></div><div class="task-actions"><button type="button" data-action="edit" aria-label="Edit ${escapeHtml(task.title)}" title="Edit task">✎</button><button type="button" data-action="delete" aria-label="Delete ${escapeHtml(task.title)}" title="Delete task">×</button></div></article>`; }
  function escapeHtml(value) { return value.replace(/[&<>'"]/g, (character) => ({ "&": "&amp;", "<": "&lt;", ">": "&gt;", "'": "&#39;", '"': "&quot;" }[character])); }
  function renderProgress() { const total = state.tasks.length; const completed = state.tasks.filter((task) => task.completed).length; const percent = total ? Math.round(completed / total * 100) : 0; elements.progressRing.style.setProperty("--progress", `${percent}%`); elements.progressValue.textContent = `${percent}%`; elements.progressCopy.textContent = total && percent === 100 ? "Everything is complete" : total ? `${completed} of ${total} complete` : "A clean slate"; }
  function resetForm() { state.editingId = null; elements.form.reset(); elements.submit.innerHTML = 'Add task <span aria-hidden="true">↗</span>'; elements.cancelEdit.classList.add("hidden"); document.querySelector("#form-title").textContent = "Add a task"; }
  function startEdit(task) { state.editingId = task.id; elements.title.value = task.title; elements.category.value = task.category; elements.priority.value = task.priority; elements.dueDate.value = task.dueDate; elements.recurrence.value = task.recurrence; elements.submit.textContent = "Save changes"; elements.cancelEdit.classList.remove("hidden"); document.querySelector("#form-title").textContent = "Edit task"; elements.title.focus(); }
  function submitTask(event) { event.preventDefault(); const title = elements.title.value.trim(); if (!title) return elements.title.focus(); const editing = Boolean(state.editingId); const values = { title, category: elements.category.value, priority: elements.priority.value, dueDate: elements.dueDate.value, recurrence: elements.recurrence.value, updatedAt: Date.now() }; if (editing) state.tasks = state.tasks.map((task) => task.id === state.editingId ? { ...task, ...values } : task); else state.tasks.unshift(normalizeTask({ ...values, id: crypto.randomUUID(), completed: false, createdAt: Date.now() })); const saved = saveTasks(); resetForm(); render(); if (saved) showToast(editing ? "Task updated" : "Task added"); }
  function nextDueDate(value, recurrence) { const date = parseDate(value); if (!date || recurrence === "none") return value; if (recurrence === "daily") date.setDate(date.getDate() + 1); if (recurrence === "weekly") date.setDate(date.getDate() + 7); if (recurrence === "monthly") date.setMonth(date.getMonth() + 1); return dateKey(date); }
  function toggleTask(id) { const task = state.tasks.find((item) => item.id === id); if (!task) return; if (!task.completed && task.recurrence !== "none" && task.dueDate) state.tasks.push({ ...task, id: crypto.randomUUID(), completed: false, dueDate: nextDueDate(task.dueDate, task.recurrence), createdAt: Date.now(), updatedAt: Date.now() }); state.tasks = state.tasks.map((item) => item.id === id ? { ...item, completed: !item.completed, updatedAt: Date.now() } : item); saveTasks(); render(); }
  function deleteTask(id) { const task = state.tasks.find((item) => item.id === id); state.tasks = state.tasks.filter((item) => item.id !== id); state.deletedTasks = task ? [task] : []; saveTasks(); render(); showToast("Task deleted", "Undo"); }
  function undoDelete() { if (!state.deletedTasks.length) return; state.tasks.push(...state.deletedTasks); state.deletedTasks = []; saveTasks(); render(); showToast("Task restored"); }
  function showToast(message, action = "") { clearTimeout(toastTimer); elements.toastMessage.textContent = message; elements.toastAction.textContent = action; elements.toastAction.classList.toggle("hidden", !action); elements.toast.classList.remove("hidden"); toastTimer = setTimeout(() => elements.toast.classList.add("hidden"), 4200); }
  elements.form.addEventListener("submit", submitTask); elements.cancelEdit.addEventListener("click", resetForm); elements.search.addEventListener("input", (event) => { state.query = event.target.value; renderTasks(); }); elements.sort.addEventListener("change", (event) => { state.sort = event.target.value; renderTasks(); });
  document.querySelectorAll("[data-status]").forEach((button) => button.addEventListener("click", () => { state.status = button.dataset.status; document.querySelectorAll("[data-status]").forEach((item) => { const active = item === button; item.classList.toggle("active", active); item.setAttribute("aria-pressed", String(active)); }); render(); }));
  document.querySelectorAll("[data-filter]").forEach((button) => button.addEventListener("click", () => { state.filter = button.dataset.filter; document.querySelectorAll("[data-filter]").forEach((item) => { const active = item === button; item.classList.toggle("active", active); item.setAttribute("aria-pressed", String(active)); }); renderTasks(); }));
  elements.list.addEventListener("click", (event) => { const action = event.target.closest("[data-action]")?.dataset.action; const card = event.target.closest("[data-id]"); if (!action || !card) return; const task = state.tasks.find((item) => item.id === card.dataset.id); if (action === "toggle") toggleTask(task.id); if (action === "edit") startEdit(task); if (action === "delete") deleteTask(task.id); });
  elements.emptyAction.addEventListener("click", () => { if (state.query || state.filter !== "all" || state.status !== "all") { state.query = ""; state.filter = "all"; state.status = "all"; elements.search.value = ""; document.querySelectorAll("[data-status]").forEach((item) => { const active = item.dataset.status === "all"; item.classList.toggle("active", active); item.setAttribute("aria-pressed", String(active)); }); document.querySelectorAll("[data-filter]").forEach((item) => { const active = item.dataset.filter === "all"; item.classList.toggle("active", active); item.setAttribute("aria-pressed", String(active)); }); render(); } else elements.title.focus(); });
  elements.toastAction.addEventListener("click", undoDelete); document.querySelector("#clear-completed").addEventListener("click", () => { const completed = state.tasks.filter((task) => task.completed); if (!completed.length) return showToast("No completed tasks to clear"); state.deletedTasks = completed; state.tasks = state.tasks.filter((task) => !task.completed); const saved = saveTasks(); render(); if (saved) showToast(`${completed.length} task${completed.length === 1 ? "" : "s"} cleared`, "Undo"); });
  elements.todayLabel.textContent = new Date().toLocaleDateString(undefined, { weekday: "long", month: "short", day: "numeric" }); render();
})();